In [1]:
import numpy as np


In [2]:
c = np.arange(10)

In [3]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
d=np.array([9, 0.9,6,10])

In [5]:
d

array([ 9. ,  0.9,  6. , 10. ])

In [6]:
c.dtype

dtype('int32')

In [7]:
d.dtype

dtype('float64')

In [8]:
f = np.zeros(10)

In [9]:
f

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
s = np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [11]:
b = np.zeros((2,3), dtype = 'float')

In [12]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
e = np.ones((2,3), dtype = 'float')

In [14]:
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
g = np.full((2),10) #full() is used to print same number as repetaed times for a single array

In [16]:
g

array([10, 10])

In [17]:
h = np.full((3,5),6) #for multidimensional array

In [18]:
h

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [19]:
i = np.arange(0,20,2) #step size 

In [20]:
i

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.linspace(0,1,10) #linspace is used to print range of btw two numbers(0,1) with step parameter(10).

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
np.random.random((3,3)) #random() is used to print random values btw 0 to 1.

array([[0.90507643, 0.74596962, 0.33403102],
       [0.438288  , 0.47390977, 0.13241666],
       [0.97576631, 0.9316452 , 0.57941155]])

In [23]:
np.random.randint((3,3))

array([1, 1])

In [24]:
np.random.normal(1,2,(3,3)) # normal always gives float values.

array([[ 3.46455402, -0.53669568, -3.19108446],
       [ 0.67266808, -0.17233574,  2.33853292],
       [ 1.83792222,  3.18857645, -1.59407397]])

In [25]:
np.random.randint(2,10,(3,3))#randint gives int values.

array([[5, 7, 3],
       [5, 8, 3],
       [8, 2, 3]])

In [26]:
np.eye(4) #identical matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.empty(2) #previously stored values in the existed memory.

array([5.43230922e-312, 7.29112202e-304])

In [29]:
h = np.arange(4)

In [30]:
h

array([0, 1, 2, 3])

In [31]:
h+5

array([5, 6, 7, 8])

In [32]:
h-5

array([-5, -4, -3, -2])

In [33]:
h/5

array([0. , 0.2, 0.4, 0.6])

In [34]:
h*5

array([ 0,  5, 10, 15])

In [35]:
h**5

array([  0,   1,  32, 243], dtype=int32)

In [36]:
h//5

array([0, 0, 0, 0], dtype=int32)

In [37]:
h%5

array([0, 1, 2, 3], dtype=int32)

In [38]:
i =np.array([1,2,3,4])

In [39]:
i

array([1, 2, 3, 4])

In [40]:
np.add(i,2)

array([3, 4, 5, 6])

In [41]:
np.subtract(i,2)

array([-1,  0,  1,  2])

In [42]:
np.multiply(i,2)

array([2, 4, 6, 8])

In [43]:
np.divide(i,2)

array([0.5, 1. , 1.5, 2. ])

In [44]:
np.floor_divide(i,2) #quotient will give

array([0, 1, 1, 2], dtype=int32)

In [45]:
np.power(i,2)

array([ 1,  4,  9, 16], dtype=int32)

In [46]:
np.mod(i,2) # % modulus = remainder will give

array([1, 0, 1, 0], dtype=int32)

In [47]:
j = np.array([-1,2,-3,4,-4])

In [48]:
j

array([-1,  2, -3,  4, -4])

In [49]:
abs(j) #absolute(abs) alwqys gives + values.

array([1, 2, 3, 4, 4])

In [54]:
k = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])

In [55]:
k

array([3.-4.j, 4.-3.j, 2.+0.j, 0.+1.j])

In [56]:
abs(k)

array([5., 5., 2., 1.])

In [57]:
np.pi

3.141592653589793

In [66]:
l = np.array([2,5,0,8,4,9,3,1])

In [67]:
l

array([2, 5, 0, 8, 4, 9, 3, 1])

In [72]:
np.sort(l)

array([0, 1, 2, 3, 4, 5, 8, 9])

In [76]:
lst = np.array([1,2,3,4,5,6])

In [77]:
lst

array([1, 2, 3, 4, 5, 6])

In [78]:
lst.mean()

3.5

In [83]:
lst.max()

6

In [84]:
lst.min()

1

In [85]:
np.median(lst)

3.5

In [87]:
np.var(lst) #variance

2.9166666666666665

In [90]:
np.std(lst) #standard deviation

1.707825127659933

In [96]:
lst.sum()

21

In [98]:
np.prod(lst) #product

720

In [101]:
q = np.random.randint(100,size=10)

In [102]:
q

array([97, 74, 26, 27,  5, 19, 60, 62, 50, 57])

In [103]:
q[1],q[4],q[6]

(74, 5, 60)

In [106]:
q[1:4:2] # slicing

array([74, 27])